### ISSUE TITLE
Add prettier in devDependencies + scripts > format inside package.json

### ISSUE THREAD

**Issue by ajax333221** [ajax333221/isepic-chess#39]
Since v8.4.7 the code should be formatted with prettier.

But to be able to format the code without having VScode + prettier extension, it should use the NPM dependency instead.

So it should be added in devDependencies and add the script to run it (inside package.json).

**Comment by arnab4477** [comment]
Done. Please check the PR.

**Comment by ajax333221** [comment]
https://github.com/ajax333221/isepic-chess/pull/40 fixes the issue, thanks (-: @arnab4477
